import './globals.css'
import Link from 'next/link'
// head 태그용, 상단바 등
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar">
                <Link href="/">홈</Link>
                <Link href="/list">상품 목록</Link>
                <Link href="/cart">카트</Link>
            </div>
        {children}
        {/* childeren = page.js 보여주기 */}
        {/* next.js 표현식
        1. 옆에 layout.js 있으면 page.js 싸맴
        2. 상위폴더에 layout.js 있으면 그걸로 한번 싸맴
        3. layout > layout > layout > page.js가 됨
        404 여러 표현식 사용 시 사용 */}
        </body>
    </html>
  )
}
